name: GlobalMarket
main: me.dasfaust.gm.Core
version: '@version@'
permissions:
   globalmarket.use:
       default: true
   globalmarket.admin:
       default: op
depends: [ProtocolLib, Vault]
loadbefore: [GlobalMarketAdditions]